<% branch_name = `git symbolic-ref HEAD 2>/dev/null`.chomp.sub('refs/heads/', '') %>
<% repository_name = `git rev-parse --show-toplevel`.split('/').last.strip %>

development:
  adapter: mysql2
  encoding: utf8
  database: <%= repository_name %>_development
  pool: 5
  username:
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: <%= repository_name %>_test
  pool: 5
  username:
  password:

qa:
  adapter: mysql2
  encoding: utf8
  database: <%= repository_name %>_qa
  pool: 5
  username:
  password:

staging:
  adapter: mysql2
  encoding: utf8
  database: <%= repository_name %>_staging
  pool: 5
  username:
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: <%= repository_name %>_production
  pool: 5
  username:
  password:
